### PR TITLE
Use full archive for game assets

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by ElonSatoshi** [comment]
Awesome! I'll test this when I get a chance.

**Comment by ghisvail** [comment]
> Awesome! I'll test this when I get a chance.

Great. Let me know your feedback and I'll merge your PR and then mine if satisfactory.

**Comment by CKKGaming** [comment]
It works 100% as normal. Now we just need it commited to the master branch.

**Comment by ghisvail** [comment]
> It works 100% as normal.

Thanks for the feedback :+1: 

> Now we just need it commited to the master branch.

I am awaiting @ElonSatoshi final review since he's the author of the original PR.

It's great having more people involved with maintenance of this Flatpak. Thank you all for this.

**Comment by CKKGaming** [comment]
> It's great having more people involved with maintenance of this Flatpak. Thank you all for this.
Even though all I did was install and provide feedback, I'm glad I was useful. If there's another problem, I'll attempt to assist. Just let me know.

**Comment by ghisvail** [comment]
> If there's another problem, I'll attempt to assist.

Please do :-)

The more eyes watching this Flatpak, the better the quality will get.

**Comment by ghisvail** [comment]
@ElonSatoshi Could you find some time for final testing? Otherwise, I am happy to merge things as is. Cheers.

**Comment by ElonSatoshi** [comment]
Here's my final review: It works great, besides a bunch of unlockables like night mode or whatever being instantly unlocked after I connect to a multiplayer server, but that seems like an issue with SRB2, not the flatpak. Go ahead and merge!

**Pull request merged**
